1 1
2 2
2b
2v
3 3
3m
3o
3p
3v
aanw
adv-pron
afgebr
afk
agr
basis
bep
betr
bez
bijz
comp C
conj
dat D
deeleigen
det
dial
dim d
eigen
enof
ev e
evf
evmo
evon
evz
excl
fem
fin
gen G
genus
genus.stan
getal
getal-n
gra
grad
hoofd
inf i
init
masc
met-e E
met-s
met-t
mv m
mv-n
nadr
neven
nom
nomin
obl
od
onbep
onder
onverst
onz
pers
persoon
postnom
pr
prenom
pron
pv
rang
recip
red
refl
rest
rest3
soort
stan
sup S
symb
tgw t
vb
vd
verl v
versm
vij
vol
vr
vreemd
vrij
zijd
zonder
zonder-n
