.TH frog-dp-update 1 "2012 February 9"

.SH NAME
frog-dp-update - A simple script to install the dependency parser files for frog
.SH SYNOPSYS
frog-dp-update

sudo frog-dp-update

.SH DESCRIPTION
Frog is packed without the (rather large) files for the dependency parser.
This script will attempt to download them and place them in de frog config 
directory.
Also any frog.cfg file found, is backed up to frog.cfg.<n> and replaced with
a new frog.cfg. This also enables support for IOB chunking.

You might need root privileges, while the frog config can be installed in
a system directory like /etc/frog

.SH OPTIONS
none

.SH AUTHORS
Ko van der Sloot Timbl@uvt.nl

Antal van den Bosch Timbl@uvt.nl

.SH SEE ALSO
.BR frog (1)
