.TH mblem 1 "2012 June 27"

.SH NAME
mblem - Dutch lemmatizer
.SH SYNOPSYS
mblem -t test-file

.SH DESCRIPTION
mblem will tokenize, tag, and lemmatize word tokens in Dutch text files.

.SH OPTIONS

.BR -c " <configfile>"
.RS
set the configuration using 'file'
.RE

.BR -d " <level>"
.RS
set debug level.
.RE

.BR -a
.RS
Give ALL analysis, not just the 'best' ones.
.RE

.BR -h
.RS
give some help
.RE

.BR -t " <file>"
.RS
process 'file'
.RE

.SH BUGS
likely

.SH AUTHORS
Ko van der Sloot Timbl@uvt.nl

Antal van den Bosch Timbl@uvt.nl

.SH SEE ALSO
.BR frog (1)
.BR mbma (1)
