.TH mblem 1 "2015 October 06"

.SH NAME
mblem - (dutch) lemmatizer
.SH SYNOPSIS
mblem -t test-file

.SH DESCRIPTION
mblem will tokenize, tag, and lemmatize word tokens in Dutch text files.

.SH OPTIONS

.BR -c " <configfile>"
.RS
set the configuration using 'file' The default is to use the Frog config file.
.RE

.BR -d " <level>"
.RS
set debug level.
.RE

.BR --notagger
.RS
Don't use a tagger to disambiguate. All variants are shown.
The default is to use the Dutch CGN tagger.
.RE

.BR --notokenizer
.RS
Don't use a tokenizer. Assume al input to be tokenized.
The default is to use the Ucto Tokenizer for Dutch.
.RE

.BR -h
.RS
give some help
.RE

.BR -t " <file>"
.RS
process 'file'
.RE

.SH BUGS
likely

.SH AUTHORS
Ko van der Sloot Timbl@uvt.nl

Antal van den Bosch Timbl@uvt.nl

.SH SEE ALSO
.BR frog (1)
.BR ucto (1)
.BR mbma (1)
